export const cards = [
    { id: 1, name: "Archer Queen", image: "/images/archer-queen.avif" },
    { id: 2, name: "Archers", image: "/images/archers.avif" },
    { id: 3, name: "Arrows", image: "/images/arrows.avif" },
    { id: 4, name: "Baby Dragon", image: "/images/baby-dragon.avif" },
    { id: 5, name: "Balloon", image: "/images/balloon.avif" },
    { id: 6, name: "Bandit", image: "/images/bandit.avif" },
    { id: 7, name: "Barbarian Barrel", image: "/images/barbarian-barrel.avif" },
    { id: 8, name: "Barbarians", image: "/images/barbarians.webp" },
    { id: 9, name: "Barbarian Hut", image: "/images/barbarian-hut.avif" },
    { id: 10, name: "Bats", image: "/images/bats.avif" },
    { id: 11, name: "Battle Healer", image: "/images/battle-healer.avif" },
    { id: 12, name: "Battle Ram", image: "/images/battle-ram.avif" },
    { id: 13, name: "Berserker", image: "/images/berserker.avif" },
    { id: 14, name: "Bomb Tower", image: "/images/bomb-tower.avif" },
    { id: 15, name: "Bomber", image: "/images/bomber.avif" },
    { id: 16, name: "Boss Bandit", image: "/images/boss-bandit.avif" },
    { id: 17, name: "Bowler", image: "/images/bowler.avif" },
    { id: 18, name: "Cannon Cart", image: "/images/cannon-cart.avif" },
    { id: 19, name: "Cannon", image: "/images/cannon.avif" },
    { id: 20, name: "Clone", image: "/images/clone.avif" },
    { id: 21, name: "Dark Prince", image: "/images/dark-prince.avif" },
    { id: 22, name: "Dart Goblin", image: "/images/dart-goblin.avif" },
    { id: 23, name: "Earthquake", image: "/images/earthquake.avif" },
    { id: 24, name: "Electro Dragon", image: "/images/electro-dragon.avif" },
    { id: 25, name: "Electro Giant", image: "/images/electro-giant.avif" },
    { id: 26, name: "Electro Spirit", image: "/images/electro-spirit.avif" },
    { id: 27, name: "Electro Wizard", image: "/images/electro-wizard.avif" },
    { id: 28, name: "Elite Barbarians", image: "/images/elite-barbarians.avif" },
    { id: 29, name: "Elixir Collector", image: "/images/elixir-collector.avif" },
    { id: 30, name: "Elixir Golem", image: "/images/elixir-golem.avif" },
    { id: 31, name: "Executioner", image: "/images/executioner.avif" },
    { id: 32, name: "Fire Spirit", image: "/images/fire-spirit.avif" },
    { id: 33, name: "Fireball", image: "/images/fireball.avif" },
    { id: 34, name: "Firecracker", image: "/images/firecracker.avif" },
    { id: 35, name: "Fisherman", image: "/images/fisherman.avif" },
    { id: 36, name: "Flying Machine", image: "/images/flying-machine.avif" },
    { id: 37, name: "Freeze", image: "/images/freeze.avif" },
    { id: 38, name: "Furnace", image: "/images/furnace.avif" },
    { id: 39, name: "Giant Skeleton", image: "/images/giant-skeleton.avif" },
    { id: 40, name: "Giant Snowball", image: "/images/giant-snowball.avif" },
    { id: 41, name: "Giant", image: "/images/giant.avif" },
    { id: 42, name: "Goblin Barrel", image: "/images/goblin-barrel.avif" },
    { id: 43, name: "Goblin Cage", image: "/images/goblin-cage.avif" },
    { id: 44, name: "Goblin Curse", image: "/images/goblin-curse.avif" },
    { id: 45, name: "Goblin Demolisher", image: "/images/goblin-demolisher.avif" },
    { id: 46, name: "Goblin Drill", image: "/images/goblin-drill.avif" },
    { id: 47, name: "Goblin Gang", image: "/images/goblin-gang.avif" },
    { id: 48, name: "Goblin Giant", image: "/images/goblin-giant.avif" },
    { id: 49, name: "Goblin Hut", image: "/images/goblin-hut.avif" },
    { id: 50, name: "Goblin Machine", image: "/images/goblin-machine.avif" },
    { id: 51, name: "Goblins", image: "/images/goblins.avif" },
    { id: 52, name: "Goblinstein", image: "/images/goblinstein.avif" },
    { id: 53, name: "Golden Knight", image: "/images/golden-knight.avif" },
    { id: 54, name: "Golem", image: "/images/golem.avif" },
    { id: 55, name: "Graveyard", image: "/images/graveyard.avif" },
    { id: 56, name: "Guards", image: "/images/guards.avif" },
    { id: 57, name: "Heal Spirit", image: "/images/heal-spirit.avif" },
    { id: 58, name: "Hog Rider", image: "/images/hog-rider.avif" },
    { id: 59, name: "Hunter", image: "/images/hunter.avif" },
    { id: 60, name: "Ice Golem", image: "/images/ice-golem.avif" },
    { id: 61, name: "Ice Spirit", image: "/images/ice-spirit.avif" },
    { id: 62, name: "Ice Wizard", image: "/images/ice-wizard.avif" },
    { id: 63, name: "Inferno Dragon", image: "/images/inferno-dragon.avif" },
    { id: 64, name: "Inferno Tower", image: "/images/inferno-tower.avif" },
    { id: 65, name: "Knight", image: "/images/knight.avif" },
    { id: 66, name: "Lava Hound", image: "/images/lava-hound.avif" },
    { id: 67, name: "Lightning", image: "/images/lightning.avif" },
    { id: 68, name: "Little Prince", image: "/images/little-prince.avif" },
    { id: 69, name: "Lumberjack", image: "/images/lumberjack.avif" },
    { id: 70, name: "Magic Archer", image: "/images/magic-archer.avif" },
    { id: 71, name: "Mega Knight", image: "/images/mega-knight.avif" },
    { id: 72, name: "Mega Minion", image: "/images/mega-minion.avif" },
    { id: 73, name: "Mighty Miner", image: "/images/mighty-miner.avif" },
    { id: 74, name: "Miner", image: "/images/miner.avif" },
    { id: 75, name: "Mini P.E.K.K.A", image: "/images/mini-pekka.avif" },
    { id: 76, name: "Minion Horde", image: "/images/minion-horde.avif" },
    { id: 77, name: "Minions", image: "/images/minions.avif" },
    { id: 78, name: "Mirror", image: "/images/mirror.avif" },
    { id: 79, name: "Monk", image: "/images/monk.avif" },
    { id: 80, name: "Mortar", image: "/images/mortar.avif" },
    { id: 81, name: "Mother Witch", image: "/images/mother-witch.avif" },
    { id: 82, name: "Musketeer", image: "/images/musketeer.avif" },
    { id: 83, name: "Night Witch", image: "/images/night-witch.avif" },
    { id: 84, name: "P.E.K.K.A", image: "/images/pekka.avif" },
    { id: 85, name: "Phoenix", image: "/images/phoenix.avif" },
    { id: 86, name: "Poison", image: "/images/poison.avif" },
    { id: 87, name: "Prince", image: "/images/prince.avif" },
    { id: 88, name: "Princess", image: "/images/princess.avif" },
    { id: 89, name: "Rage", image: "/images/rage.avif" },
    { id: 90, name: "Ram Rider", image: "/images/ram-rider.avif" },
    { id: 91, name: "Rascals", image: "/images/rascals.avif" },
    { id: 92, name: "Rocket", image: "/images/rocket.avif" },
    { id: 93, name: "Royal Delivery", image: "/images/royal-delivery.avif" },
    { id: 94, name: "Royal Ghost", image: "/images/royal-ghost.avif" },
    { id: 95, name: "Royal Giant", image: "/images/royal-giant.avif" },
    { id: 96, name: "Royal Hogs", image: "/images/royal-hogs.avif" },
    { id: 97, name: "Royal Recruits", image: "/images/royal-recruits.avif" },
    { id: 98, name: "Rune Giant", image: "/images/rune-giant.avif" },
    { id: 99, name: "Skeleton Army", image: "/images/skeleton-army.avif" },
    { id: 100, name: "Skeleton Barrel", image: "/images/skeleton-barrel.avif" },
    { id: 101, name: "Skeleton Dragons", image: "/images/skeleton-dragons.avif" },
    { id: 102, name: "Skeleton King", image: "/images/skeleton-king.avif" },
    { id: 103, name: "Skeletons", image: "/images/skeletons.avif" },
    { id: 104, name: "Sparky", image: "/images/sparky.avif" },
    { id: 105, name: "Spear Goblins", image: "/images/spear-goblins.avif" },
    { id: 106, name: "Spirit Empress", image: "/images/spirit-empress.avif" },
    { id: 107, name: "Suspicious Bush", image: "/images/suspicious-bush.avif" },
    { id: 108, name: "Tesla", image: "/images/tesla.avif" },
    { id: 109, name: "The Log", image: "/images/the-log.avif" },
    { id: 110, name: "Three Musketeers", image: "/images/three-musketeers.avif" },
    { id: 111, name: "Tombstone", image: "/images/tombstone.avif" },
    { id: 112, name: "Tornado", image: "/images/tornado.avif" },
    { id: 113, name: "Valkyrie", image: "/images/valkyrie.avif" },
    { id: 114, name: "Vines", image: "/images/vines.avif" },
    { id: 115, name: "Void", image: "/images/void.avif" },
    { id: 116, name: "Wall Breakers", image: "/images/wall-breakers.avif" },
    { id: 117, name: "Witch", image: "/images/witch.avif" },
    { id: 118, name: "Wizard", image: "/images/wizard.avif" },
    { id: 119, name: "X-Bow", image: "/images/x-bow.avif" },
    { id: 120, name: "Zap", image: "/images/zap.avif" },
    { id: 121, name: "Zappies", image: "/images/zappies.avif" },
  ];  

export default function AllCards() {
    return (
        <main className="p-8">
            <div className="grid grid-cols-7 gap-4">
                {cards.map((card, i) => (
                <div key={i} className="flex flex-col items-center">
                    <h1 className="text-2xl">{card.name}</h1>
                    <img src={card.image} />
                </div>
                ))}
            </div>
        </main>
    );
}